# Generated by Django 5.0.1 on 2024-02-15 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('materials', '0002_material_is_published_material_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='material',
            name='views_count',
            field=models.IntegerField(default=0, verbose_name='Просмотров'),
        ),
    ]
